### ISSUE TITLE
blank create page

### ISSUE THREAD

**Issue by epkev** [bemosior/PHPasswordPusher#26]
I recently set PHPasswordPusher on a centos 6 vm. I can bring up the main page and type in a password to share, but when I submit, the create page is blank. Any insight would be appreciated.

![untitled](https://f.cloud.github.com/assets/4482792/538524/c2c6ab10-c18d-11e2-9db2-ab6e12fb3c43.png)

-Thanks

**Comment by vaindil** [comment]
@epkev Were you able to solve this? I know this was two years ago, but I'm facing the same problem at the moment.

**Comment by bemosior** [comment]
Oh wow. Software that I haven't looked at in years. This should be interesting.

I set up a quick Centos 6.6 Vagrant VM and ran through the install steps. I see the same problem.

**Comment by bemosior** [comment]
And in the apache error_log:

```
PHP Fatal error:  Call to undefined function mcrypt_encrypt() in /vagrant/pwpusher_private/security.php on line 19, referer: http://localhost:8080/pass/pw.php```

**Comment by bemosior** [comment]
Edit `/etc/php.ini` and add `extension=mcrypt.so` to fix the error. I'll update the documentation.

Let me know if that fixes it for you as well.

**Comment by bemosior** [comment]
I suspect this was the same issue experienced in #27.

**Comment by vaindil** [comment]
Ah, perfect, thanks! Just a note though--I believe the "correct" method is to run `php5enmod mcrypt` rather than manually adding the extension to `php.ini`. It'll update things as appropriate and throw an error if `mcrypt` doesn't exist. I also prefer this method because my `php.ini` file (Ubuntu 15.04) is actually in `/etc/php5/apache2`. Just a thought. Thanks again!

**Comment by bemosior** [comment]
I was not aware `php5enmod` was even a thing. I'll update the documentation. Thanks!
